name: Load NPM Cache
description: Load cached npm package data into the global npm cache
runs:
  using: composite
  steps:
    - name: Cache global ~/.npm cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.2.0
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-
