name: Test

on:
  pull_request:
    branches:
      - develop
      - dev-[0-9]+.[0-9]+.[0-9]+
    types:
      # defaults + 'edited', to handle changes to flags like ___REQUIRES_GATEWAY_PR___ in the PR body
      [ opened, synchronize, reopened, edited ]
  push:
    branches:
      - develop
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

env:
  AERIE_USERNAME: "${{secrets.AERIE_USERNAME}}"
  AERIE_PASSWORD: "${{secrets.AERIE_PASSWORD}}"
  HASURA_GRAPHQL_ADMIN_SECRET: "${{secrets.HASURA_GRAPHQL_ADMIN_SECRET}}"
  HASURA_GRAPHQL_JWT_SECRET: "${{secrets.HASURA_GRAPHQL_JWT_SECRET}}"
  POSTGRES_USER: "${{secrets.POSTGRES_USER}}"
  POSTGRES_PASSWORD: "${{secrets.POSTGRES_PASSWORD}}"
  GATEWAY_USERNAME: "${{secrets.GATEWAY_USERNAME}}"
  GATEWAY_PASSWORD: "${{secrets.GATEWAY_PASSWORD}}"
  MERLIN_USERNAME: "${{secrets.MERLIN_USERNAME}}"
  MERLIN_PASSWORD: "${{secrets.MERLIN_PASSWORD}}"
  SCHEDULER_USERNAME: "${{secrets.SCHEDULER_USERNAME}}"
  SCHEDULER_PASSWORD: "${{secrets.SCHEDULER_PASSWORD}}"
  SEQUENCING_USERNAME: "${{secrets.SEQUENCING_USERNAME}}"
  SEQUENCING_PASSWORD: "${{secrets.SEQUENCING_PASSWORD}}"
  PR_BODY: "${{github.event.pull_request.body}}"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Load NPM Cache
        uses: ./.github/actions/load-node-cache
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          # This action defaults to matching on "main" and "master" as the branches allowed to write to the cache
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Assemble
        # Don't generate docs for tests
        run: ./gradlew assemble -x javadoc -x javadocJar -x generateDocumentation --parallel
      - name: Run Unit Tests
        run: ./gradlew test --parallel
      - name: Upload Test Results as XML and HTML
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Unit Test Results
          path: |
            **/build/test-results/test
            **/build/reports/tests/test

  action-unit-tests:
    runs-on: ubuntu-latest
    environment: e2e-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup NPM
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ./action-server/.nvmrc
          cache: npm
          cache-dependency-path: ./action-server/package-lock.json
      - name: Install Dependencies
        run: npm ci
        working-directory: ./action-server
      - name: Run Action Server Unit Tests
        run: npm --silent run test
        working-directory: ./action-server
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Action Server Test Results
          path: |
            **/action-server/action-server-test-report.log

  db-tests:
    runs-on: ubuntu-latest
    environment: e2e-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Postgres Client (psql)
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          # This action defaults to matching on "main" and "master" as the branches allowed to write to the cache
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Start Services
        run: |
          docker compose -f ./e2e-tests/docker-compose-test.yml up postgres -d --quiet-pull
      - name: Sleep for 5 Seconds
        run: sleep 5s
        shell: bash
      - name: Run DB Tests
        run: ./gradlew db-tests:e2eTest
      - name: Upload DB Test Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: DB Test Results
          path: |
            **/db-tests/build/reports/tests/e2eTest
      - name: Shutdown Backend
        uses: ./.github/actions/shutdown-test-backend

  sequencing-e2e-tests:
    runs-on: ubuntu-latest
    environment: e2e-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          # This action defaults to matching on "main" and "master" as the branches allowed to write to the cache
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Start E2E Test Backend
        uses: ./.github/actions/start-test-backend
      - name: Run Sequencing E2E Tests
        run: ./gradlew sequencing-server:e2eTest
      - name: Upload Sequencing E2E Test Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Sequencing E2E Test Results
          path: |
            **/sequencing-server/test-report.*
      - name: Shutdown E2E Test Backend
        uses: ./.github/actions/shutdown-test-backend

  java-e2e-test:
    runs-on: ubuntu-latest
    environment: e2e-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          # This action defaults to matching on "main" and "master" as the branches allowed to write to the cache
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Start E2E Test Backend
        uses: ./.github/actions/start-test-backend
      - name: Build scheduling procedure jars for testing
        run: ./gradlew e2e-tests:buildAllProcedureJars
      - name: Run E2E Tests
        run: ./gradlew e2e-tests:e2eTest
      - name: Upload E2E Test Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: E2E Test Results
          path: |
            **/e2e-tests/build/reports/tests/e2eTest
      - name: Shutdown Backend
        uses: ./.github/actions/shutdown-test-backend
